### ISSUE TITLE
Error installing (Windows 7)

### ISSUE THREAD

**Issue by Sandwich247** [crocokyle/XMRGUI#6]
When I click the installer, the initialising bar appears, but an error appears immediately after stating:

System.IO.InvalidDataException: Central Directory corrupt. --->
System.IO.IOException: An attempt was made to move the file pointer
before the beginning of the file.

  at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
  at System.IO.FileStream.SeekCore(Int64offset, SeekOrigin origin)
  at System.IO.FileStream.Seek(Int64offset, SeekOrigin origin)
  at System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory()
  --- End of inner exception stack trace ---
  at System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory()
  at System.IO.Compression.ZipArchive.Init(Stream stream, ZipArchiveMode
mode, Boolean leaveOpen)
  at System.IO.Compression.ZipArchive..ctor(Stream stream,
ZipArchiveMode mode, Boolean leaveOPen, Encoding entryNameEncoding)
  at System.IO.Compression.ZipFile.OPen(String archiveFileName,
ZipArchiveMode mode, Encoding entryNameEncoding)
  at System.IO.Compression.ZipFile.OpenRead(String archiveFileName)
  atXMRGUI.Form1.UnZip()

When I click OK, the installer moved the to "How much do you know about mining?" window.
When I choose any of the options, click on start, then run, it comes up with the "Checking For new updates..." bar. Application does nothing after this point.

If I close down the program, and open up the xmrgui.exe from AppData\Roaming\XMRGUI, it again hangs on the "Checking For new updates..." bar.

**Comment by slinkyvagabond** [comment]
Same behaviour on Windows 10 Pro when installing V1.9. Also will not compile from source (or, at least, not for me) in VS 2019.
